apiVersion: v1
kind: Namespace
metadata:
  name: kubeopt-com
  labels:
    app.kubernetes.io/name: kubeopt-com
    app.kubernetes.io/part-of: kubeopt-platform
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubectl
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: kubeopt-com-quota
  namespace: kubeopt-com
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "10"
    services: "5"
    persistentvolumeclaims: "2"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: kubeopt-com-limits
  namespace: kubeopt-com
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    max:
      cpu: "2"
      memory: 2Gi
    min:
      cpu: 50m
      memory: 64Mi
    type: Container